gwengolo_admin_homepage:
    path:     /admin/
    defaults: { _controller: GwengoloAdminBundle:Default:index }

gwengolo_admin_collection_search:
    path:     /admin/collection/search
    defaults: { _controller: GwengoloAdminBundle:Collection:search }

gwengolo_admin_collection_add:
    path:     /admin/collection/add
    defaults: { _controller: GwengoloAdminBundle:Collection:add }

gwengolo_admin_newsletter_watch:
    path:     /admin/newsletter/watch
    defaults: { _controller: GwengoloAdminBundle:Default:newsletter }

gwengolo_admin_collection_edit:
    path:     /admin/collection/edit/{id}
    defaults: { _controller: GwengoloAdminBundle:Collection:edit }

gwengolo_admin_collection_delete:
    path:     /admin/collection/delete/{id}
    defaults: { _controller: GwengoloAdminBundle:Collection:delete }

gwengolo_admin_product_search:
    path:     /admin/product/search
    defaults: { _controller: GwengoloAdminBundle:Product:search }

gwengolo_admin_product_add:
    path:     /admin/product/add
    defaults: { _controller: GwengoloAdminBundle:Product:add }

gwengolo_admin_product_edit:
    path:     /admin/product/edit/{id}
    defaults: { _controller: GwengoloAdminBundle:Product:edit }

gwengolo_admin_product_delete:
    path:     /admin/product/delete/{id}
    defaults: { _controller: GwengoloAdminBundle:Product:delete }

gwengolo_admin_type_search:
    path:     /admin/type/search
    defaults: { _controller: GwengoloAdminBundle:Type:search }

gwengolo_admin_type_delete:
    path:     /admin/type/delete/{id}
    defaults: { _controller: GwengoloAdminBundle:Type:delete }

gwengolo_admin_type_add:
    path:     /admin/type/add
    defaults: { _controller: GwengoloAdminBundle:Type:add }

gwengolo_admin_type_edit:
    path:     /admin/type/edit/{id}
    defaults: { _controller: GwengoloAdminBundle:Type:edit }

gwengolo_admin_color_search:
    path:     /admin/color/search
    defaults: { _controller: GwengoloAdminBundle:Color:search }

gwengolo_admin_color_delete:
    path:     /admin/color/delete/{id}
    defaults: { _controller: GwengoloAdminBundle:Color:delete }

gwengolo_admin_color_add:
    path:     /admin/color/add
    defaults: { _controller: GwengoloAdminBundle:Color:add }

gwengolo_admin_color_edit:
    path:     /admin/color/edit/{id}
    defaults: { _controller: GwengoloAdminBundle:Color:edit }

gwengolo_admin_specificity_search:
    path:     /admin/specificity/search
    defaults: { _controller: GwengoloAdminBundle:Specificity:search }

gwengolo_admin_specificity_delete:
    path:     /admin/specificity/delete/{id}
    defaults: { _controller: GwengoloAdminBundle:Specificity:delete }

gwengolo_admin_specificity_add:
    path:     /admin/specificity/add
    defaults: { _controller: GwengoloAdminBundle:Specificity:add }

gwengolo_admin_specificity_edit:
    path:     /admin/specificity/edit/{id}
    defaults: { _controller: GwengoloAdminBundle:Specificity:edit }

gwengolo_admin_image:
    path:     /admin/image/{id}
    defaults: { _controller: GwengoloAdminBundle:Image:image }

gwengolo_admin_image_upload_main:
    path:     /admin/image/mainupload/{id}
    defaults: { _controller: GwengoloAdminBundle:Image:mainUpload }

gwengolo_admin_image_upload_others:
    path:     /admin/image/othersupload/{id}
    defaults: { _controller: GwengoloAdminBundle:Image:othersUpload }

gwengolo_admin_image_delete:
    path:     /admin/image/delete/{id}/{productId}
    defaults: { _controller: GwengoloAdminBundle:Image:delete }




